# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170319_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 19, 15, 4, 240000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 19, 15, 4, 238000, tzinfo=utc)),
        ),
    ]
