# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20170321_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 21, 3, 37, 14000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 21, 3, 37, 12000, tzinfo=utc)),
        ),
    ]
