# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20170329_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 23, 38, 44, 84000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 23, 38, 44, 83000, tzinfo=utc)),
        ),
    ]
