# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_auto_20170331_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 14, 15, 47, 73000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 14, 15, 47, 71000, tzinfo=utc)),
        ),
    ]
