# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_auto_20170401_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 14, 20, 29, 979000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 14, 20, 29, 977000, tzinfo=utc)),
        ),
    ]
