# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 20, 40, 20, 594000, tzinfo=utc)),
        ),
    ]
