# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
