# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_auto_20170316_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 21, 53, 12, 984000, tzinfo=utc)),
        ),
    ]
