# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_auto_20170319_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 19, 15, 4, 154000, tzinfo=utc)),
        ),
    ]
