# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0008_auto_20170321_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 21, 3, 36, 967000, tzinfo=utc)),
        ),
    ]
