# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0009_auto_20170329_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='magazine_images'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 23, 38, 44, 31000, tzinfo=utc)),
        ),
    ]
