# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0012_auto_20170330_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
